// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type EstadisticaArquero struct {
	IDPartido         int32          `json:"id_partido"`
	GolesRecibidos    int32          `json:"goles_recibidos"`
	AtajadasClave     int32          `json:"atajadas_clave"`
	SaquesCompletados sql.NullString `json:"saques_completados"`
}

type EstadisticaJugador struct {
	IDPartido        int32          `json:"id_partido"`
	Goles            int32          `json:"goles"`
	Asistencias      int32          `json:"asistencias"`
	PasesCompletados sql.NullString `json:"pases_completados"`
	DuelosGanados    sql.NullString `json:"duelos_ganados"`
}

type Partido struct {
	IDPartido  int32     `json:"id_partido"`
	IDUsuario  int32     `json:"id_usuario"`
	Fecha      time.Time `json:"fecha"`
	Cancha     string    `json:"cancha"`
	Puntuacion int32     `json:"puntuacion"`
}

type Usuario struct {
	IDUsuario int32  `json:"id_usuario"`
	Nombre    string `json:"nombre"`
	Apellido  string `json:"apellido"`
	Pais      string `json:"pais"`
}
