// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: partidos.sql

package db

import (
	"context"
	"time"
)

const deletePartido = `-- name: DeletePartido :exec
DELETE FROM partido WHERE id_usuario = $1 AND id_partido = $2
`

type DeletePartidoParams struct {
	IDUsuario int32 `json:"id_usuario"`
	IDPartido int32 `json:"id_partido"`
}

func (q *Queries) DeletePartido(ctx context.Context, arg DeletePartidoParams) error {
	_, err := q.db.ExecContext(ctx, deletePartido, arg.IDUsuario, arg.IDPartido)
	return err
}

const getPartido = `-- name: GetPartido :one
SELECT id_partido, id_usuario, fecha, cancha, puntuacion FROM partido WHERE id_usuario = $1 AND id_partido = $2
`

type GetPartidoParams struct {
	IDUsuario int32 `json:"id_usuario"`
	IDPartido int32 `json:"id_partido"`
}

func (q *Queries) GetPartido(ctx context.Context, arg GetPartidoParams) (Partido, error) {
	row := q.db.QueryRowContext(ctx, getPartido, arg.IDUsuario, arg.IDPartido)
	var i Partido
	err := row.Scan(
		&i.IDPartido,
		&i.IDUsuario,
		&i.Fecha,
		&i.Cancha,
		&i.Puntuacion,
	)
	return i, err
}

const insertPartido = `-- name: InsertPartido :one
INSERT INTO partido(id_usuario, fecha, cancha, puntuacion) VALUES ($1, $2, $3, $4)
RETURNING id_partido, id_usuario, fecha, cancha, puntuacion
`

type InsertPartidoParams struct {
	IDUsuario  int32     `json:"id_usuario"`
	Fecha      time.Time `json:"fecha"`
	Cancha     string    `json:"cancha"`
	Puntuacion int32     `json:"puntuacion"`
}

func (q *Queries) InsertPartido(ctx context.Context, arg InsertPartidoParams) (Partido, error) {
	row := q.db.QueryRowContext(ctx, insertPartido,
		arg.IDUsuario,
		arg.Fecha,
		arg.Cancha,
		arg.Puntuacion,
	)
	var i Partido
	err := row.Scan(
		&i.IDPartido,
		&i.IDUsuario,
		&i.Fecha,
		&i.Cancha,
		&i.Puntuacion,
	)
	return i, err
}

const listPartidos = `-- name: ListPartidos :many
SELECT id_partido, id_usuario, fecha, cancha, puntuacion FROM partido WHERE id_usuario = $1
`

func (q *Queries) ListPartidos(ctx context.Context, idUsuario int32) ([]Partido, error) {
	rows, err := q.db.QueryContext(ctx, listPartidos, idUsuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partido
	for rows.Next() {
		var i Partido
		if err := rows.Scan(
			&i.IDPartido,
			&i.IDUsuario,
			&i.Fecha,
			&i.Cancha,
			&i.Puntuacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartido = `-- name: UpdatePartido :exec
UPDATE partido SET puntuacion = $2
WHERE id_usuario = $1
`

type UpdatePartidoParams struct {
	IDUsuario  int32 `json:"id_usuario"`
	Puntuacion int32 `json:"puntuacion"`
}

func (q *Queries) UpdatePartido(ctx context.Context, arg UpdatePartidoParams) error {
	_, err := q.db.ExecContext(ctx, updatePartido, arg.IDUsuario, arg.Puntuacion)
	return err
}
