// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usuarios.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO usuario(nombre, apellido, pais) VALUES ($1, $2, $3)
RETURNING id_usuario, nombre, apellido, pais
`

type CreateUserParams struct {
	Nombre   string `json:"nombre"`
	Apellido string `json:"apellido"`
	Pais     string `json:"pais"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Nombre, arg.Apellido, arg.Pais)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.Nombre,
		&i.Apellido,
		&i.Pais,
	)
	return i, err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM usuario WHERE id_usuario = $1
`

func (q *Queries) DeleteUsuario(ctx context.Context, idUsuario int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, idUsuario)
	return err
}

const getAllUser = `-- name: GetAllUser :many
SELECT id_usuario, nombre, apellido, pais FROM usuario
`

func (q *Queries) GetAllUser(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, getAllUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.IDUsuario,
			&i.Nombre,
			&i.Apellido,
			&i.Pais,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsuario = `-- name: GetUsuario :one
SELECT id_usuario, nombre, apellido, pais FROM usuario WHERE id_usuario = $1
`

func (q *Queries) GetUsuario(ctx context.Context, idUsuario int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, idUsuario)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.Nombre,
		&i.Apellido,
		&i.Pais,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE usuario SET nombre=$2, apellido=$3, pais=$4 WHERE id_usuario = $1
RETURNING id_usuario, nombre, apellido, pais
`

type UpdateUserParams struct {
	IDUsuario int32  `json:"id_usuario"`
	Nombre    string `json:"nombre"`
	Apellido  string `json:"apellido"`
	Pais      string `json:"pais"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.IDUsuario,
		arg.Nombre,
		arg.Apellido,
		arg.Pais,
	)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.Nombre,
		&i.Apellido,
		&i.Pais,
	)
	return i, err
}
